default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  <% if ENV["DB_HOST"] %>
  host: <%= ENV["DB_HOST"] %>
  username: postgres
  password: postgres
  <% end %>

development:
  primary:
    <<: *default
    database: orthodox_production
  cache:
    <<: *default
    database: orthodox_cache
    migrations_path: db/cache_schema
  queue:
    <<: *default
    database: orthodox_queue
    migrations_path: db/queue_schema
  cable:
    <<: *default
    database: orthodox_cable
    migrations_path: db/cable_schema

test:
  <<: *default
  database: orthodox_test

production:
  primary:
    <<: *default
    database: orthodox_production
  cache:
    <<: *default
    database: orthodox_cache
    migrations_path: db/cache_schema
  queue:
    <<: *default
    database: orthodox_queue
    migrations_path: db/queue_schema
  cable:
    <<: *default
    database: orthodox_cable
    migrations_path: db/cable_schema

